# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic_sensor_appearance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import icon_path_pb2 as icon__path__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='basic_sensor_appearance.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x1d\x62\x61sic_sensor_appearance.proto\x12\x06goosci\x1a\x0ficon_path.proto\"\xcf\x01\n\x15\x42\x61sicSensorAppearance\x12\x0e\n\x06locale\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05units\x18\x03 \x01(\t\x12#\n\ticon_path\x18\x04 \x01(\x0b\x32\x10.goosci.IconPath\x12\x19\n\x11short_description\x18\x05 \x01(\t\x12\x1e\n\x12pointsAfterDecimal\x18\x06 \x01(\x05:\x02-1\x12)\n\x0flarge_icon_path\x18\x07 \x01(\x0b\x32\x10.goosci.IconPathBU\n3com.google.android.apps.forscience.whistlepunk.dataB\x16GoosciSensorAppearanceH\x03\xa2\x02\x03GSJ')
  ,
  dependencies=[icon__path__pb2.DESCRIPTOR,])




_BASICSENSORAPPEARANCE = _descriptor.Descriptor(
  name='BasicSensorAppearance',
  full_name='goosci.BasicSensorAppearance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locale', full_name='goosci.BasicSensorAppearance.locale', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='goosci.BasicSensorAppearance.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='units', full_name='goosci.BasicSensorAppearance.units', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon_path', full_name='goosci.BasicSensorAppearance.icon_path', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='short_description', full_name='goosci.BasicSensorAppearance.short_description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pointsAfterDecimal', full_name='goosci.BasicSensorAppearance.pointsAfterDecimal', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='large_icon_path', full_name='goosci.BasicSensorAppearance.large_icon_path', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=266,
)

_BASICSENSORAPPEARANCE.fields_by_name['icon_path'].message_type = icon__path__pb2._ICONPATH
_BASICSENSORAPPEARANCE.fields_by_name['large_icon_path'].message_type = icon__path__pb2._ICONPATH
DESCRIPTOR.message_types_by_name['BasicSensorAppearance'] = _BASICSENSORAPPEARANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BasicSensorAppearance = _reflection.GeneratedProtocolMessageType('BasicSensorAppearance', (_message.Message,), dict(
  DESCRIPTOR = _BASICSENSORAPPEARANCE,
  __module__ = 'basic_sensor_appearance_pb2'
  # @@protoc_insertion_point(class_scope:goosci.BasicSensorAppearance)
  ))
_sym_db.RegisterMessage(BasicSensorAppearance)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3com.google.android.apps.forscience.whistlepunk.dataB\026GoosciSensorAppearanceH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
