# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: icon_path.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='icon_path.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x0ficon_path.proto\x12\x06goosci\"y\n\x08IconPath\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.goosci.IconPath.PathType\x12\x13\n\x0bpath_string\x18\x02 \x01(\t\"/\n\x08PathType\x12\x0b\n\x07\x42UILTIN\x10\x00\x12\x16\n\x12LEGACY_ANDROID_BLE\x10\x01\x42I\n3com.google.android.apps.forscience.whistlepunk.dataB\nGoosciIconH\x03\xa2\x02\x03GSJ')
)



_ICONPATH_PATHTYPE = _descriptor.EnumDescriptor(
  name='PathType',
  full_name='goosci.IconPath.PathType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUILTIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEGACY_ANDROID_BLE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=101,
  serialized_end=148,
)
_sym_db.RegisterEnumDescriptor(_ICONPATH_PATHTYPE)


_ICONPATH = _descriptor.Descriptor(
  name='IconPath',
  full_name='goosci.IconPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='goosci.IconPath.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path_string', full_name='goosci.IconPath.path_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ICONPATH_PATHTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=148,
)

_ICONPATH.fields_by_name['type'].enum_type = _ICONPATH_PATHTYPE
_ICONPATH_PATHTYPE.containing_type = _ICONPATH
DESCRIPTOR.message_types_by_name['IconPath'] = _ICONPATH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IconPath = _reflection.GeneratedProtocolMessageType('IconPath', (_message.Message,), dict(
  DESCRIPTOR = _ICONPATH,
  __module__ = 'icon_path_pb2'
  # @@protoc_insertion_point(class_scope:goosci.IconPath)
  ))
_sym_db.RegisterMessage(IconPath)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3com.google.android.apps.forscience.whistlepunk.dataB\nGoosciIconH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
