# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input_device.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='input_device.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x12input_device.proto\x12\x06goosci\"@\n\x11InputDeviceConfig\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65vice_address\x18\x02 \x01(\tBJ\n3com.google.android.apps.forscience.whistlepunk.dataB\x0bInputDeviceH\x03\xa2\x02\x03GSJ')
)




_INPUTDEVICECONFIG = _descriptor.Descriptor(
  name='InputDeviceConfig',
  full_name='goosci.InputDeviceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider_id', full_name='goosci.InputDeviceConfig.provider_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_address', full_name='goosci.InputDeviceConfig.device_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['InputDeviceConfig'] = _INPUTDEVICECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputDeviceConfig = _reflection.GeneratedProtocolMessageType('InputDeviceConfig', (_message.Message,), dict(
  DESCRIPTOR = _INPUTDEVICECONFIG,
  __module__ = 'input_device_pb2'
  # @@protoc_insertion_point(class_scope:goosci.InputDeviceConfig)
  ))
_sym_db.RegisterMessage(InputDeviceConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3com.google.android.apps.forscience.whistlepunk.dataB\013InputDeviceH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
