# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='label_value.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x11label_value.proto\x12\x06goosci\"\xda\x01\n\nLabelValue\x12*\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1c.goosci.LabelValue.DataEntry\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.goosci.LabelValue.ValueType\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"G\n\tValueType\x12\x08\n\x04TEXT\x10\x01\x12\x0b\n\x07PICTURE\x10\x02\x12\x12\n\x0eSENSOR_TRIGGER\x10\x03\x12\x0f\n\x0b\x41PPLICATION\x10\x04\x42S\n7com.google.android.apps.forscience.whistlepunk.metadataB\x10GoosciLabelValueH\x03\xa2\x02\x03GSJ')
)



_LABELVALUE_VALUETYPE = _descriptor.EnumDescriptor(
  name='ValueType',
  full_name='goosci.LabelValue.ValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PICTURE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_TRIGGER', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPLICATION', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=177,
  serialized_end=248,
)
_sym_db.RegisterEnumDescriptor(_LABELVALUE_VALUETYPE)


_LABELVALUE_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='goosci.LabelValue.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='goosci.LabelValue.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='goosci.LabelValue.DataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=175,
)

_LABELVALUE = _descriptor.Descriptor(
  name='LabelValue',
  full_name='goosci.LabelValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='goosci.LabelValue.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='goosci.LabelValue.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LABELVALUE_DATAENTRY, ],
  enum_types=[
    _LABELVALUE_VALUETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=248,
)

_LABELVALUE_DATAENTRY.containing_type = _LABELVALUE
_LABELVALUE.fields_by_name['data'].message_type = _LABELVALUE_DATAENTRY
_LABELVALUE.fields_by_name['type'].enum_type = _LABELVALUE_VALUETYPE
_LABELVALUE_VALUETYPE.containing_type = _LABELVALUE
DESCRIPTOR.message_types_by_name['LabelValue'] = _LABELVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LabelValue = _reflection.GeneratedProtocolMessageType('LabelValue', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _LABELVALUE_DATAENTRY,
    __module__ = 'label_value_pb2'
    # @@protoc_insertion_point(class_scope:goosci.LabelValue.DataEntry)
    ))
  ,
  DESCRIPTOR = _LABELVALUE,
  __module__ = 'label_value_pb2'
  # @@protoc_insertion_point(class_scope:goosci.LabelValue)
  ))
_sym_db.RegisterMessage(LabelValue)
_sym_db.RegisterMessage(LabelValue.DataEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\020GoosciLabelValueH\003\242\002\003GSJ'))
_LABELVALUE_DATAENTRY.has_options = True
_LABELVALUE_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
