# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: picture_label_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='picture_label_value.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x19picture_label_value.proto\x12\x06goosci\"%\n\x11PictureLabelValue\x12\x10\n\x08\x66ilePath\x18\x01 \x01(\tBZ\n7com.google.android.apps.forscience.whistlepunk.metadataB\x17GoosciPictureLabelValueH\x03\xa2\x02\x03GSJ')
)




_PICTURELABELVALUE = _descriptor.Descriptor(
  name='PictureLabelValue',
  full_name='goosci.PictureLabelValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filePath', full_name='goosci.PictureLabelValue.filePath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['PictureLabelValue'] = _PICTURELABELVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PictureLabelValue = _reflection.GeneratedProtocolMessageType('PictureLabelValue', (_message.Message,), dict(
  DESCRIPTOR = _PICTURELABELVALUE,
  __module__ = 'picture_label_value_pb2'
  # @@protoc_insertion_point(class_scope:goosci.PictureLabelValue)
  ))
_sym_db.RegisterMessage(PictureLabelValue)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\027GoosciPictureLabelValueH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
