# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scalar_input_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scalar_input_config.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19scalar_input_config.proto\"\xa9\x02\n\x11ScalarInputConfig\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x13\n\x07icon_id\x18\x03 \x01(\x05:\x02-1\x12\x0f\n\x05units\x18\x04 \x01(\t:\x00\x12\x1b\n\x11short_description\x18\x05 \x01(\t:\x00\x12\x14\n\nlogging_id\x18\x06 \x01(\t:\x00\x12,\n\x1eshould_show_options_on_connect\x18\x07 \x01(\x08:\x04true\x12*\n\x1forder_in_experiment_api_sensors\x18\x08 \x01(\x05:\x01\x30\x12\'\n\x1b\x65xpected_samples_per_second\x18\t \x01(\x02:\x02\x31\x30\x12\x13\n\tdevice_id\x18\n \x01(\t:\x00\x42J\n3com.google.android.apps.forscience.whistlepunk.dataB\x11GoosciScalarInputH\x03')
)




_SCALARINPUTCONFIG = _descriptor.Descriptor(
  name='ScalarInputConfig',
  full_name='ScalarInputConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_id', full_name='ScalarInputConfig.service_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='ScalarInputConfig.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon_id', full_name='ScalarInputConfig.icon_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='units', full_name='ScalarInputConfig.units', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='short_description', full_name='ScalarInputConfig.short_description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logging_id', full_name='ScalarInputConfig.logging_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='should_show_options_on_connect', full_name='ScalarInputConfig.should_show_options_on_connect', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_in_experiment_api_sensors', full_name='ScalarInputConfig.order_in_experiment_api_sensors', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expected_samples_per_second', full_name='ScalarInputConfig.expected_samples_per_second', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='ScalarInputConfig.device_id', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=327,
)

DESCRIPTOR.message_types_by_name['ScalarInputConfig'] = _SCALARINPUTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScalarInputConfig = _reflection.GeneratedProtocolMessageType('ScalarInputConfig', (_message.Message,), dict(
  DESCRIPTOR = _SCALARINPUTCONFIG,
  __module__ = 'scalar_input_config_pb2'
  # @@protoc_insertion_point(class_scope:ScalarInputConfig)
  ))
_sym_db.RegisterMessage(ScalarInputConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3com.google.android.apps.forscience.whistlepunk.dataB\021GoosciScalarInputH\003'))
# @@protoc_insertion_point(module_scope)
