# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_trigger_label_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_spec_pb2 as sensor__spec__pb2
import sensor_trigger_information_pb2 as sensor__trigger__information__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_trigger_label_value.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n sensor_trigger_label_value.proto\x12\x06goosci\x1a\x11sensor_spec.proto\x1a sensor_trigger_information.proto\"u\n\x17SensorTriggerLabelValue\x12\"\n\x06sensor\x18\x01 \x01(\x0b\x32\x12.goosci.SensorSpec\x12\x36\n\x12triggerInformation\x18\x02 \x01(\x0b\x32\x1a.goosci.TriggerInformationB`\n7com.google.android.apps.forscience.whistlepunk.metadataB\x1dGoosciSensorTriggerLabelValueH\x03\xa2\x02\x03GSJ')
  ,
  dependencies=[sensor__spec__pb2.DESCRIPTOR,sensor__trigger__information__pb2.DESCRIPTOR,])




_SENSORTRIGGERLABELVALUE = _descriptor.Descriptor(
  name='SensorTriggerLabelValue',
  full_name='goosci.SensorTriggerLabelValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor', full_name='goosci.SensorTriggerLabelValue.sensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triggerInformation', full_name='goosci.SensorTriggerLabelValue.triggerInformation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=214,
)

_SENSORTRIGGERLABELVALUE.fields_by_name['sensor'].message_type = sensor__spec__pb2._SENSORSPEC
_SENSORTRIGGERLABELVALUE.fields_by_name['triggerInformation'].message_type = sensor__trigger__information__pb2._TRIGGERINFORMATION
DESCRIPTOR.message_types_by_name['SensorTriggerLabelValue'] = _SENSORTRIGGERLABELVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorTriggerLabelValue = _reflection.GeneratedProtocolMessageType('SensorTriggerLabelValue', (_message.Message,), dict(
  DESCRIPTOR = _SENSORTRIGGERLABELVALUE,
  __module__ = 'sensor_trigger_label_value_pb2'
  # @@protoc_insertion_point(class_scope:goosci.SensorTriggerLabelValue)
  ))
_sym_db.RegisterMessage(SensorTriggerLabelValue)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\035GoosciSensorTriggerLabelValueH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
