# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_trigger_information.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_trigger_information.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n sensor_trigger_information.proto\x12\x06goosci\"\xb9\x05\n\x12TriggerInformation\x12\x16\n\x0evalueToTrigger\x18\x03 \x01(\x01\x12;\n\x0btriggerWhen\x18\x04 \x01(\x0e\x32&.goosci.TriggerInformation.TriggerWhen\x12G\n\x11triggerActionType\x18\x05 \x01(\x0e\x32,.goosci.TriggerInformation.TriggerActionType\x12\x46\n\x11triggerAlertTypes\x18\x06 \x03(\x0e\x32+.goosci.TriggerInformation.TriggerAlertType\x12\x10\n\x08noteText\x18\x07 \x01(\t\x12\'\n\x18triggerOnlyWhenRecording\x18\x08 \x01(\x08:\x05\x66\x61lse\"\x8e\x01\n\x0bTriggerWhen\x12\x13\n\x0fTRIGGER_WHEN_AT\x10\x00\x12\x1c\n\x18TRIGGER_WHEN_RISES_ABOVE\x10\x01\x12\x1c\n\x18TRIGGER_WHEN_DROPS_BELOW\x10\x02\x12\x16\n\x12TRIGGER_WHEN_ABOVE\x10\x03\x12\x16\n\x12TRIGGER_WHEN_BELOW\x10\x04\"\x8d\x01\n\x11TriggerActionType\x12\"\n\x1eTRIGGER_ACTION_START_RECORDING\x10\x00\x12!\n\x1dTRIGGER_ACTION_STOP_RECORDING\x10\x01\x12\x17\n\x13TRIGGER_ACTION_NOTE\x10\x02\x12\x18\n\x14TRIGGER_ACTION_ALERT\x10\x03\"a\n\x10TriggerAlertType\x12\x18\n\x14TRIGGER_ALERT_VISUAL\x10\x01\x12\x17\n\x13TRIGGER_ALERT_AUDIO\x10\x02\x12\x1a\n\x16TRIGGER_ALERT_PHYSICAL\x10\x03\x42\x61\n7com.google.android.apps.forscience.whistlepunk.metadataB\x1eGoosciSensorTriggerInformationH\x03\xa2\x02\x03GSJ')
)



_TRIGGERINFORMATION_TRIGGERWHEN = _descriptor.EnumDescriptor(
  name='TriggerWhen',
  full_name='goosci.TriggerInformation.TriggerWhen',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_WHEN_AT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_WHEN_RISES_ABOVE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_WHEN_DROPS_BELOW', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_WHEN_ABOVE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_WHEN_BELOW', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=357,
  serialized_end=499,
)
_sym_db.RegisterEnumDescriptor(_TRIGGERINFORMATION_TRIGGERWHEN)

_TRIGGERINFORMATION_TRIGGERACTIONTYPE = _descriptor.EnumDescriptor(
  name='TriggerActionType',
  full_name='goosci.TriggerInformation.TriggerActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_ACTION_START_RECORDING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_ACTION_STOP_RECORDING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_ACTION_NOTE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_ACTION_ALERT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=502,
  serialized_end=643,
)
_sym_db.RegisterEnumDescriptor(_TRIGGERINFORMATION_TRIGGERACTIONTYPE)

_TRIGGERINFORMATION_TRIGGERALERTTYPE = _descriptor.EnumDescriptor(
  name='TriggerAlertType',
  full_name='goosci.TriggerInformation.TriggerAlertType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_ALERT_VISUAL', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_ALERT_AUDIO', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_ALERT_PHYSICAL', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=645,
  serialized_end=742,
)
_sym_db.RegisterEnumDescriptor(_TRIGGERINFORMATION_TRIGGERALERTTYPE)


_TRIGGERINFORMATION = _descriptor.Descriptor(
  name='TriggerInformation',
  full_name='goosci.TriggerInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valueToTrigger', full_name='goosci.TriggerInformation.valueToTrigger', index=0,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triggerWhen', full_name='goosci.TriggerInformation.triggerWhen', index=1,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triggerActionType', full_name='goosci.TriggerInformation.triggerActionType', index=2,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triggerAlertTypes', full_name='goosci.TriggerInformation.triggerAlertTypes', index=3,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noteText', full_name='goosci.TriggerInformation.noteText', index=4,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triggerOnlyWhenRecording', full_name='goosci.TriggerInformation.triggerOnlyWhenRecording', index=5,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRIGGERINFORMATION_TRIGGERWHEN,
    _TRIGGERINFORMATION_TRIGGERACTIONTYPE,
    _TRIGGERINFORMATION_TRIGGERALERTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=742,
)

_TRIGGERINFORMATION.fields_by_name['triggerWhen'].enum_type = _TRIGGERINFORMATION_TRIGGERWHEN
_TRIGGERINFORMATION.fields_by_name['triggerActionType'].enum_type = _TRIGGERINFORMATION_TRIGGERACTIONTYPE
_TRIGGERINFORMATION.fields_by_name['triggerAlertTypes'].enum_type = _TRIGGERINFORMATION_TRIGGERALERTTYPE
_TRIGGERINFORMATION_TRIGGERWHEN.containing_type = _TRIGGERINFORMATION
_TRIGGERINFORMATION_TRIGGERACTIONTYPE.containing_type = _TRIGGERINFORMATION
_TRIGGERINFORMATION_TRIGGERALERTTYPE.containing_type = _TRIGGERINFORMATION
DESCRIPTOR.message_types_by_name['TriggerInformation'] = _TRIGGERINFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TriggerInformation = _reflection.GeneratedProtocolMessageType('TriggerInformation', (_message.Message,), dict(
  DESCRIPTOR = _TRIGGERINFORMATION,
  __module__ = 'sensor_trigger_information_pb2'
  # @@protoc_insertion_point(class_scope:goosci.TriggerInformation)
  ))
_sym_db.RegisterMessage(TriggerInformation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\036GoosciSensorTriggerInformationH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
