# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_spec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basic_sensor_appearance_pb2 as basic__sensor__appearance__pb2
import gadget_info_pb2 as gadget__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_spec.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x11sensor_spec.proto\x12\x06goosci\x1a\x1d\x62\x61sic_sensor_appearance.proto\x1a\x11gadget_info.proto\"{\n\nSensorSpec\x12 \n\x04info\x18\x01 \x01(\x0b\x32\x12.goosci.GadgetInfo\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\x0c\x12;\n\x14rememberedAppearance\x18\x03 \x01(\x0b\x32\x1d.goosci.BasicSensorAppearanceBO\n3com.google.android.apps.forscience.whistlepunk.dataB\x10GoosciSensorSpecH\x03\xa2\x02\x03GSJ')
  ,
  dependencies=[basic__sensor__appearance__pb2.DESCRIPTOR,gadget__info__pb2.DESCRIPTOR,])




_SENSORSPEC = _descriptor.Descriptor(
  name='SensorSpec',
  full_name='goosci.SensorSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='goosci.SensorSpec.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='goosci.SensorSpec.config', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rememberedAppearance', full_name='goosci.SensorSpec.rememberedAppearance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=202,
)

_SENSORSPEC.fields_by_name['info'].message_type = gadget__info__pb2._GADGETINFO
_SENSORSPEC.fields_by_name['rememberedAppearance'].message_type = basic__sensor__appearance__pb2._BASICSENSORAPPEARANCE
DESCRIPTOR.message_types_by_name['SensorSpec'] = _SENSORSPEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorSpec = _reflection.GeneratedProtocolMessageType('SensorSpec', (_message.Message,), dict(
  DESCRIPTOR = _SENSORSPEC,
  __module__ = 'sensor_spec_pb2'
  # @@protoc_insertion_point(class_scope:goosci.SensorSpec)
  ))
_sym_db.RegisterMessage(SensorSpec)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3com.google.android.apps.forscience.whistlepunk.dataB\020GoosciSensorSpecH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
