# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_trigger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_trigger_information_pb2 as sensor__trigger__information__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_trigger.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x14sensor_trigger.proto\x12\x06goosci\x1a sensor_trigger_information.proto\"\x80\x01\n\rSensorTrigger\x12\x10\n\x08sensorId\x18\x01 \x01(\t\x12\x12\n\nlastUsedMs\x18\x02 \x01(\x03\x12\x36\n\x12triggerInformation\x18\x03 \x01(\x0b\x32\x1a.goosci.TriggerInformation\x12\x11\n\ttriggerId\x18\x04 \x01(\tBV\n7com.google.android.apps.forscience.whistlepunk.metadataB\x13GoosciSensorTriggerH\x03\xa2\x02\x03GSJ')
  ,
  dependencies=[sensor__trigger__information__pb2.DESCRIPTOR,])




_SENSORTRIGGER = _descriptor.Descriptor(
  name='SensorTrigger',
  full_name='goosci.SensorTrigger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorId', full_name='goosci.SensorTrigger.sensorId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastUsedMs', full_name='goosci.SensorTrigger.lastUsedMs', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triggerInformation', full_name='goosci.SensorTrigger.triggerInformation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triggerId', full_name='goosci.SensorTrigger.triggerId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=195,
)

_SENSORTRIGGER.fields_by_name['triggerInformation'].message_type = sensor__trigger__information__pb2._TRIGGERINFORMATION
DESCRIPTOR.message_types_by_name['SensorTrigger'] = _SENSORTRIGGER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorTrigger = _reflection.GeneratedProtocolMessageType('SensorTrigger', (_message.Message,), dict(
  DESCRIPTOR = _SENSORTRIGGER,
  __module__ = 'sensor_trigger_pb2'
  # @@protoc_insertion_point(class_scope:goosci.SensorTrigger)
  ))
_sym_db.RegisterMessage(SensorTrigger)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\023GoosciSensorTriggerH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
