# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_config.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x13sensor_config.proto\x12\x06goosci\"\x95\x02\n\x0f\x42leSensorConfig\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x13\n\x0bsensor_type\x18\x02 \x01(\t\x12\x11\n\tcustomPin\x18\x03 \x01(\t\x12\x17\n\x0f\x63ustomFrequency\x18\x04 \x01(\x08\x12\x44\n\x14\x63ustomScaleTransform\x18\x05 \x01(\x0b\x32&.goosci.BleSensorConfig.ScaleTransform\x1aj\n\x0eScaleTransform\x12\x17\n\x0csourceBottom\x18\x01 \x01(\x01:\x01\x30\x12\x14\n\tsourceTop\x18\x02 \x01(\x01:\x01\x31\x12\x15\n\ndestBottom\x18\x03 \x01(\x01:\x01\x30\x12\x12\n\x07\x64\x65stTop\x18\x04 \x01(\x01:\x01\x31\x42Q\n3com.google.android.apps.forscience.whistlepunk.dataB\x12GoosciSensorConfigH\x03\xa2\x02\x03GSJ')
)




_BLESENSORCONFIG_SCALETRANSFORM = _descriptor.Descriptor(
  name='ScaleTransform',
  full_name='goosci.BleSensorConfig.ScaleTransform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sourceBottom', full_name='goosci.BleSensorConfig.ScaleTransform.sourceBottom', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sourceTop', full_name='goosci.BleSensorConfig.ScaleTransform.sourceTop', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destBottom', full_name='goosci.BleSensorConfig.ScaleTransform.destBottom', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destTop', full_name='goosci.BleSensorConfig.ScaleTransform.destTop', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=309,
)

_BLESENSORCONFIG = _descriptor.Descriptor(
  name='BleSensorConfig',
  full_name='goosci.BleSensorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='goosci.BleSensorConfig.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_type', full_name='goosci.BleSensorConfig.sensor_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customPin', full_name='goosci.BleSensorConfig.customPin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customFrequency', full_name='goosci.BleSensorConfig.customFrequency', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customScaleTransform', full_name='goosci.BleSensorConfig.customScaleTransform', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BLESENSORCONFIG_SCALETRANSFORM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=309,
)

_BLESENSORCONFIG_SCALETRANSFORM.containing_type = _BLESENSORCONFIG
_BLESENSORCONFIG.fields_by_name['customScaleTransform'].message_type = _BLESENSORCONFIG_SCALETRANSFORM
DESCRIPTOR.message_types_by_name['BleSensorConfig'] = _BLESENSORCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BleSensorConfig = _reflection.GeneratedProtocolMessageType('BleSensorConfig', (_message.Message,), dict(

  ScaleTransform = _reflection.GeneratedProtocolMessageType('ScaleTransform', (_message.Message,), dict(
    DESCRIPTOR = _BLESENSORCONFIG_SCALETRANSFORM,
    __module__ = 'sensor_config_pb2'
    # @@protoc_insertion_point(class_scope:goosci.BleSensorConfig.ScaleTransform)
    ))
  ,
  DESCRIPTOR = _BLESENSORCONFIG,
  __module__ = 'sensor_config_pb2'
  # @@protoc_insertion_point(class_scope:goosci.BleSensorConfig)
  ))
_sym_db.RegisterMessage(BleSensorConfig)
_sym_db.RegisterMessage(BleSensorConfig.ScaleTransform)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3com.google.android.apps.forscience.whistlepunk.dataB\022GoosciSensorConfigH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
