# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshot_label_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_spec_pb2 as sensor__spec__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='snapshot_label_value.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x1asnapshot_label_value.proto\x12\x06goosci\x1a\x11sensor_spec.proto\"\xac\x01\n\x12SnapshotLabelValue\x12<\n\tsnapshots\x18\x01 \x03(\x0b\x32).goosci.SnapshotLabelValue.SensorSnapshot\x1aX\n\x0eSensorSnapshot\x12\"\n\x06sensor\x18\x01 \x01(\x0b\x32\x12.goosci.SensorSpec\x12\x13\n\x0btimestampMs\x18\x02 \x01(\x03\x12\r\n\x05value\x18\x03 \x01(\x01\x42V\n7com.google.android.apps.forscience.whistlepunk.metadataB\x13GoosciSnapshotValueH\x03\xa2\x02\x03GSJ')
  ,
  dependencies=[sensor__spec__pb2.DESCRIPTOR,])




_SNAPSHOTLABELVALUE_SENSORSNAPSHOT = _descriptor.Descriptor(
  name='SensorSnapshot',
  full_name='goosci.SnapshotLabelValue.SensorSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor', full_name='goosci.SnapshotLabelValue.SensorSnapshot.sensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestampMs', full_name='goosci.SnapshotLabelValue.SensorSnapshot.timestampMs', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='goosci.SnapshotLabelValue.SensorSnapshot.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=230,
)

_SNAPSHOTLABELVALUE = _descriptor.Descriptor(
  name='SnapshotLabelValue',
  full_name='goosci.SnapshotLabelValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshots', full_name='goosci.SnapshotLabelValue.snapshots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SNAPSHOTLABELVALUE_SENSORSNAPSHOT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=230,
)

_SNAPSHOTLABELVALUE_SENSORSNAPSHOT.fields_by_name['sensor'].message_type = sensor__spec__pb2._SENSORSPEC
_SNAPSHOTLABELVALUE_SENSORSNAPSHOT.containing_type = _SNAPSHOTLABELVALUE
_SNAPSHOTLABELVALUE.fields_by_name['snapshots'].message_type = _SNAPSHOTLABELVALUE_SENSORSNAPSHOT
DESCRIPTOR.message_types_by_name['SnapshotLabelValue'] = _SNAPSHOTLABELVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SnapshotLabelValue = _reflection.GeneratedProtocolMessageType('SnapshotLabelValue', (_message.Message,), dict(

  SensorSnapshot = _reflection.GeneratedProtocolMessageType('SensorSnapshot', (_message.Message,), dict(
    DESCRIPTOR = _SNAPSHOTLABELVALUE_SENSORSNAPSHOT,
    __module__ = 'snapshot_label_value_pb2'
    # @@protoc_insertion_point(class_scope:goosci.SnapshotLabelValue.SensorSnapshot)
    ))
  ,
  DESCRIPTOR = _SNAPSHOTLABELVALUE,
  __module__ = 'snapshot_label_value_pb2'
  # @@protoc_insertion_point(class_scope:goosci.SnapshotLabelValue)
  ))
_sym_db.RegisterMessage(SnapshotLabelValue)
_sym_db.RegisterMessage(SnapshotLabelValue.SensorSnapshot)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\023GoosciSnapshotValueH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
