# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_label_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='text_label_value.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x16text_label_value.proto\x12\x06goosci\"\x1e\n\x0eTextLabelValue\x12\x0c\n\x04text\x18\x01 \x01(\tBW\n7com.google.android.apps.forscience.whistlepunk.metadataB\x14GoosciTextLabelValueH\x03\xa2\x02\x03GSJ')
)




_TEXTLABELVALUE = _descriptor.Descriptor(
  name='TextLabelValue',
  full_name='goosci.TextLabelValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='goosci.TextLabelValue.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['TextLabelValue'] = _TEXTLABELVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextLabelValue = _reflection.GeneratedProtocolMessageType('TextLabelValue', (_message.Message,), dict(
  DESCRIPTOR = _TEXTLABELVALUE,
  __module__ = 'text_label_value_pb2'
  # @@protoc_insertion_point(class_scope:goosci.TextLabelValue)
  ))
_sym_db.RegisterMessage(TextLabelValue)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\024GoosciTextLabelValueH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
