# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trial.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basic_sensor_appearance_pb2 as basic__sensor__appearance__pb2
import caption_pb2 as caption__pb2
import label_pb2 as label__pb2
import sensor_layout_pb2 as sensor__layout__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trial.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x0btrial.proto\x12\x06goosci\x1a\x1d\x62\x61sic_sensor_appearance.proto\x1a\rcaption.proto\x1a\x0blabel.proto\x1a\x13sensor_layout.proto\"\x99\x04\n\x05Trial\x12\x0f\n\x07trialId\x18\x01 \x01(\t\x12\x16\n\x0e\x63reationTimeMs\x18\x02 \x01(\x03\x12\r\n\x05title\x18\x03 \x01(\t\x12\x17\n\x08\x61rchived\x18\x04 \x01(\x08:\x05\x66\x61lse\x12%\n\x0erecordingRange\x18\x05 \x01(\x0b\x32\r.goosci.Range\x12 \n\tcropRange\x18\x06 \x01(\x0b\x32\r.goosci.Range\x12\x1d\n\x0f\x61utoZoomEnabled\x18\x07 \x01(\x08:\x04true\x12+\n\rsensorLayouts\x18\x08 \x03(\x0b\x32\x14.goosci.SensorLayout\x12,\n\ntrialStats\x18\t \x03(\x0b\x32\x18.goosci.SensorTrialStats\x12\x1d\n\x06labels\x18\n \x03(\x0b\x32\r.goosci.Label\x12 \n\x07\x63\x61ption\x18\x0b \x01(\x0b\x32\x0f.goosci.Caption\x12\x38\n\x11sensorAppearances\x18\x0c \x03(\x0b\x32\x1d.goosci.Trial.AppearanceEntry\x12\x1f\n\x17trialNumberInExperiment\x18\r \x01(\x05\x1a`\n\x0f\x41ppearanceEntry\x12\x10\n\x08sensorId\x18\x01 \x01(\t\x12;\n\x14rememberedAppearance\x18\x02 \x01(\x0b\x32\x1d.goosci.BasicSensorAppearance\"\'\n\x05Range\x12\x0f\n\x07startMs\x18\x01 \x01(\x03\x12\r\n\x05\x65ndMs\x18\x02 \x01(\x03\"\xb1\x01\n\x10SensorTrialStats\x12\x10\n\x08sensorId\x18\x01 \x01(\t\x12\x37\n\nstatStatus\x18\x02 \x01(\x0e\x32#.goosci.SensorTrialStats.StatStatus\x12\'\n\x0bsensorStats\x18\x03 \x03(\x0b\x32\x12.goosci.SensorStat\")\n\nStatStatus\x12\t\n\x05VALID\x10\x01\x12\x10\n\x0cNEEDS_UPDATE\x10\x02\"\xf7\x01\n\nSensorStat\x12-\n\x08statType\x18\x01 \x01(\x0e\x32\x1b.goosci.SensorStat.StatType\x12\x11\n\tstatValue\x18\x02 \x01(\x01\"\xa6\x01\n\x08StatType\x12\x0b\n\x07MINIMUM\x10\x01\x12\x0b\n\x07MAXIMUM\x10\x02\x12\x0b\n\x07\x41VERAGE\x10\x03\x12\x13\n\x0fNUM_DATA_POINTS\x10\x04\x12\x12\n\x0eTOTAL_DURATION\x10\x05\x12\x1d\n\x19ZOOM_PRESENTER_TIER_COUNT\x10\x06\x12+\n\'ZOOM_PRESENTER_ZOOM_LEVEL_BETWEEN_TIERS\x10\x07\x42N\n7com.google.android.apps.forscience.whistlepunk.metadataB\x0bGoosciTrialH\x03\xa2\x02\x03GSJ')
  ,
  dependencies=[basic__sensor__appearance__pb2.DESCRIPTOR,caption__pb2.DESCRIPTOR,label__pb2.DESCRIPTOR,sensor__layout__pb2.DESCRIPTOR,])



_SENSORTRIALSTATS_STATSTATUS = _descriptor.EnumDescriptor(
  name='StatStatus',
  full_name='goosci.SensorTrialStats.StatStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VALID', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEEDS_UPDATE', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=821,
  serialized_end=862,
)
_sym_db.RegisterEnumDescriptor(_SENSORTRIALSTATS_STATSTATUS)

_SENSORSTAT_STATTYPE = _descriptor.EnumDescriptor(
  name='StatType',
  full_name='goosci.SensorStat.StatType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MINIMUM', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXIMUM', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVERAGE', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUM_DATA_POINTS', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOTAL_DURATION', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZOOM_PRESENTER_TIER_COUNT', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZOOM_PRESENTER_ZOOM_LEVEL_BETWEEN_TIERS', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=946,
  serialized_end=1112,
)
_sym_db.RegisterEnumDescriptor(_SENSORSTAT_STATTYPE)


_TRIAL_APPEARANCEENTRY = _descriptor.Descriptor(
  name='AppearanceEntry',
  full_name='goosci.Trial.AppearanceEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorId', full_name='goosci.Trial.AppearanceEntry.sensorId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rememberedAppearance', full_name='goosci.Trial.AppearanceEntry.rememberedAppearance', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=545,
  serialized_end=641,
)

_TRIAL = _descriptor.Descriptor(
  name='Trial',
  full_name='goosci.Trial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trialId', full_name='goosci.Trial.trialId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creationTimeMs', full_name='goosci.Trial.creationTimeMs', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='goosci.Trial.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='archived', full_name='goosci.Trial.archived', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordingRange', full_name='goosci.Trial.recordingRange', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cropRange', full_name='goosci.Trial.cropRange', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='autoZoomEnabled', full_name='goosci.Trial.autoZoomEnabled', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensorLayouts', full_name='goosci.Trial.sensorLayouts', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trialStats', full_name='goosci.Trial.trialStats', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='goosci.Trial.labels', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='caption', full_name='goosci.Trial.caption', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensorAppearances', full_name='goosci.Trial.sensorAppearances', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trialNumberInExperiment', full_name='goosci.Trial.trialNumberInExperiment', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRIAL_APPEARANCEENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=641,
)


_RANGE = _descriptor.Descriptor(
  name='Range',
  full_name='goosci.Range',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startMs', full_name='goosci.Range.startMs', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endMs', full_name='goosci.Range.endMs', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=643,
  serialized_end=682,
)


_SENSORTRIALSTATS = _descriptor.Descriptor(
  name='SensorTrialStats',
  full_name='goosci.SensorTrialStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorId', full_name='goosci.SensorTrialStats.sensorId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statStatus', full_name='goosci.SensorTrialStats.statStatus', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensorStats', full_name='goosci.SensorTrialStats.sensorStats', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSORTRIALSTATS_STATSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=862,
)


_SENSORSTAT = _descriptor.Descriptor(
  name='SensorStat',
  full_name='goosci.SensorStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statType', full_name='goosci.SensorStat.statType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statValue', full_name='goosci.SensorStat.statValue', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSORSTAT_STATTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=865,
  serialized_end=1112,
)

_TRIAL_APPEARANCEENTRY.fields_by_name['rememberedAppearance'].message_type = basic__sensor__appearance__pb2._BASICSENSORAPPEARANCE
_TRIAL_APPEARANCEENTRY.containing_type = _TRIAL
_TRIAL.fields_by_name['recordingRange'].message_type = _RANGE
_TRIAL.fields_by_name['cropRange'].message_type = _RANGE
_TRIAL.fields_by_name['sensorLayouts'].message_type = sensor__layout__pb2._SENSORLAYOUT
_TRIAL.fields_by_name['trialStats'].message_type = _SENSORTRIALSTATS
_TRIAL.fields_by_name['labels'].message_type = label__pb2._LABEL
_TRIAL.fields_by_name['caption'].message_type = caption__pb2._CAPTION
_TRIAL.fields_by_name['sensorAppearances'].message_type = _TRIAL_APPEARANCEENTRY
_SENSORTRIALSTATS.fields_by_name['statStatus'].enum_type = _SENSORTRIALSTATS_STATSTATUS
_SENSORTRIALSTATS.fields_by_name['sensorStats'].message_type = _SENSORSTAT
_SENSORTRIALSTATS_STATSTATUS.containing_type = _SENSORTRIALSTATS
_SENSORSTAT.fields_by_name['statType'].enum_type = _SENSORSTAT_STATTYPE
_SENSORSTAT_STATTYPE.containing_type = _SENSORSTAT
DESCRIPTOR.message_types_by_name['Trial'] = _TRIAL
DESCRIPTOR.message_types_by_name['Range'] = _RANGE
DESCRIPTOR.message_types_by_name['SensorTrialStats'] = _SENSORTRIALSTATS
DESCRIPTOR.message_types_by_name['SensorStat'] = _SENSORSTAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Trial = _reflection.GeneratedProtocolMessageType('Trial', (_message.Message,), dict(

  AppearanceEntry = _reflection.GeneratedProtocolMessageType('AppearanceEntry', (_message.Message,), dict(
    DESCRIPTOR = _TRIAL_APPEARANCEENTRY,
    __module__ = 'trial_pb2'
    # @@protoc_insertion_point(class_scope:goosci.Trial.AppearanceEntry)
    ))
  ,
  DESCRIPTOR = _TRIAL,
  __module__ = 'trial_pb2'
  # @@protoc_insertion_point(class_scope:goosci.Trial)
  ))
_sym_db.RegisterMessage(Trial)
_sym_db.RegisterMessage(Trial.AppearanceEntry)

Range = _reflection.GeneratedProtocolMessageType('Range', (_message.Message,), dict(
  DESCRIPTOR = _RANGE,
  __module__ = 'trial_pb2'
  # @@protoc_insertion_point(class_scope:goosci.Range)
  ))
_sym_db.RegisterMessage(Range)

SensorTrialStats = _reflection.GeneratedProtocolMessageType('SensorTrialStats', (_message.Message,), dict(
  DESCRIPTOR = _SENSORTRIALSTATS,
  __module__ = 'trial_pb2'
  # @@protoc_insertion_point(class_scope:goosci.SensorTrialStats)
  ))
_sym_db.RegisterMessage(SensorTrialStats)

SensorStat = _reflection.GeneratedProtocolMessageType('SensorStat', (_message.Message,), dict(
  DESCRIPTOR = _SENSORSTAT,
  __module__ = 'trial_pb2'
  # @@protoc_insertion_point(class_scope:goosci.SensorStat)
  ))
_sym_db.RegisterMessage(SensorStat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\013GoosciTrialH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
