# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import device_spec_pb2 as device__spec__pb2
import version_pb2 as version__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_metadata.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\x13user_metadata.proto\x12\x06goosci\x1a\x11\x64\x65vice_spec.proto\x1a\rversion.proto\"\xc5\x01\n\x0cUserMetadata\x12/\n\x0b\x65xperiments\x18\x01 \x03(\x0b\x32\x1a.goosci.ExperimentOverview\x12\x16\n\x07version\x18\x02 \x01(\x05:\x01\x31\x42\x02\x18\x01\x12\x1b\n\x0cminorVersion\x18\x03 \x01(\x05:\x01\x31\x42\x02\x18\x01\x12%\n\tmyDevices\x18\x04 \x03(\x0b\x32\x12.goosci.DeviceSpec\x12(\n\x0b\x66ileVersion\x18\x05 \x01(\x0b\x32\x13.goosci.FileVersion\"\xa3\x01\n\x12\x45xperimentOverview\x12\x14\n\x0c\x65xperimentId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\timagePath\x18\x03 \x01(\t\x12\x16\n\x0elastUsedTimeMs\x18\x04 \x01(\x03\x12\x12\n\ntrialCount\x18\x05 \x01(\x05\x12\x12\n\nisArchived\x18\x06 \x01(\x08\x12\x15\n\ncolorIndex\x18\x07 \x01(\x05:\x01\x30\x42U\n7com.google.android.apps.forscience.whistlepunk.metadataB\x12GoosciUserMetadataH\x03\xa2\x02\x03GSJ')
  ,
  dependencies=[device__spec__pb2.DESCRIPTOR,version__pb2.DESCRIPTOR,])




_USERMETADATA = _descriptor.Descriptor(
  name='UserMetadata',
  full_name='goosci.UserMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='experiments', full_name='goosci.UserMetadata.experiments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='goosci.UserMetadata.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minorVersion', full_name='goosci.UserMetadata.minorVersion', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='myDevices', full_name='goosci.UserMetadata.myDevices', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileVersion', full_name='goosci.UserMetadata.fileVersion', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=263,
)


_EXPERIMENTOVERVIEW = _descriptor.Descriptor(
  name='ExperimentOverview',
  full_name='goosci.ExperimentOverview',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='experimentId', full_name='goosci.ExperimentOverview.experimentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='goosci.ExperimentOverview.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imagePath', full_name='goosci.ExperimentOverview.imagePath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastUsedTimeMs', full_name='goosci.ExperimentOverview.lastUsedTimeMs', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trialCount', full_name='goosci.ExperimentOverview.trialCount', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isArchived', full_name='goosci.ExperimentOverview.isArchived', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorIndex', full_name='goosci.ExperimentOverview.colorIndex', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=429,
)

_USERMETADATA.fields_by_name['experiments'].message_type = _EXPERIMENTOVERVIEW
_USERMETADATA.fields_by_name['myDevices'].message_type = device__spec__pb2._DEVICESPEC
_USERMETADATA.fields_by_name['fileVersion'].message_type = version__pb2._FILEVERSION
DESCRIPTOR.message_types_by_name['UserMetadata'] = _USERMETADATA
DESCRIPTOR.message_types_by_name['ExperimentOverview'] = _EXPERIMENTOVERVIEW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserMetadata = _reflection.GeneratedProtocolMessageType('UserMetadata', (_message.Message,), dict(
  DESCRIPTOR = _USERMETADATA,
  __module__ = 'user_metadata_pb2'
  # @@protoc_insertion_point(class_scope:goosci.UserMetadata)
  ))
_sym_db.RegisterMessage(UserMetadata)

ExperimentOverview = _reflection.GeneratedProtocolMessageType('ExperimentOverview', (_message.Message,), dict(
  DESCRIPTOR = _EXPERIMENTOVERVIEW,
  __module__ = 'user_metadata_pb2'
  # @@protoc_insertion_point(class_scope:goosci.ExperimentOverview)
  ))
_sym_db.RegisterMessage(ExperimentOverview)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\022GoosciUserMetadataH\003\242\002\003GSJ'))
_USERMETADATA.fields_by_name['version'].has_options = True
_USERMETADATA.fields_by_name['version']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_USERMETADATA.fields_by_name['minorVersion'].has_options = True
_USERMETADATA.fields_by_name['minorVersion']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
# @@protoc_insertion_point(module_scope)
