# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gadget_info_pb2 as gadget__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='version.proto',
  package='goosci',
  syntax='proto2',
  serialized_pb=_b('\n\rversion.proto\x12\x06goosci\x1a\x11gadget_info.proto\"\x82\x01\n\x0b\x46ileVersion\x12\x12\n\x07version\x18\x01 \x01(\x05:\x01\x31\x12\x17\n\x0cminorVersion\x18\x02 \x01(\x05:\x01\x31\x12-\n\x08platform\x18\x03 \x01(\x0e\x32\x1b.goosci.GadgetInfo.Platform\x12\x17\n\x0fplatformVersion\x18\x04 \x01(\x05\x42J\n7com.google.android.apps.forscience.whistlepunk.metadataB\x07VersionH\x03\xa2\x02\x03GSJ')
  ,
  dependencies=[gadget__info__pb2.DESCRIPTOR,])




_FILEVERSION = _descriptor.Descriptor(
  name='FileVersion',
  full_name='goosci.FileVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='goosci.FileVersion.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minorVersion', full_name='goosci.FileVersion.minorVersion', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='goosci.FileVersion.platform', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platformVersion', full_name='goosci.FileVersion.platformVersion', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=175,
)

_FILEVERSION.fields_by_name['platform'].enum_type = gadget__info__pb2._GADGETINFO_PLATFORM
DESCRIPTOR.message_types_by_name['FileVersion'] = _FILEVERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileVersion = _reflection.GeneratedProtocolMessageType('FileVersion', (_message.Message,), dict(
  DESCRIPTOR = _FILEVERSION,
  __module__ = 'version_pb2'
  # @@protoc_insertion_point(class_scope:goosci.FileVersion)
  ))
_sym_db.RegisterMessage(FileVersion)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.google.android.apps.forscience.whistlepunk.metadataB\007VersionH\003\242\002\003GSJ'))
# @@protoc_insertion_point(module_scope)
